/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS `aes_pm` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `aes_pm`;

CREATE TABLE IF NOT EXISTS `item` (
  `iId` int(10) NOT NULL AUTO_INCREMENT,
  `iClass` int(10) NOT NULL DEFAULT '0',
  `iName` varchar(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `iNumber` int(10) NOT NULL,
  `iDeadline` datetime NOT NULL DEFAULT '0000-00-15 00:00:00',
  `iWeight` int(10) NOT NULL,
  `iNote` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`iId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `user` (
  `uId` int(10) NOT NULL AUTO_INCREMENT,
  `uUser` varchar(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `uUserid` int(10) NOT NULL,
  `uItemid` int(10) NOT NULL,
  `uNumber` int(10) NOT NULL,
  `uHandler` varchar(16) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `uStart_time` datetime NOT NULL,
  `uEnd_time` datetime DEFAULT NULL,
  `uDeadline` datetime DEFAULT NULL,
  `uTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
